# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJqgGxoW9IDNtbIGpbnGZGsj0iG7V6eE
"""

from datetime import datetime


def agregar_nota():
    nota = input("Escribe tu nota: ")
    fecha = datetime.now().strftime("%Y-%m-%d %H:%M")

    with open("notas.txt", "a", encoding="utf-8") as archivo:
        archivo.write(f"[{fecha}] {nota}\n")

    print("Nota guardada correctamente ✅")


def ver_notas():
    try:
        with open("notas.txt", "r", encoding="utf-8") as archivo:
            notas = archivo.readlines()

        if not notas:
            print("No hay notas guardadas.")
        else:
            print("\n📒 TUS NOTAS:")
            for i, nota in enumerate(notas, start=1):
                print(f"{i}. {nota.strip()}")

    except FileNotFoundError:
        print("No existe el archivo de notas.")


def eliminar_nota():
    try:
        with open("notas.txt", "r", encoding="utf-8") as archivo:
            notas = archivo.readlines()

        if not notas:
            print("No hay notas para eliminar.")
            return

        ver_notas()
        num = int(input("Número de nota a eliminar: "))

        if 1 <= num <= len(notas):
            notas.pop(num - 1)
            with open("notas.txt", "w", encoding="utf-8") as archivo:
                archivo.writelines(notas)
            print("Nota eliminada 🗑️")
        else:
            print("Número inválido")

    except ValueError:
        print("Ingresa un número válido")
    except FileNotFoundError:
        print("No existe el archivo de notas.")


def buscar_nota():
    palabra = input("Palabra a buscar: ").lower()

    try:
        with open("notas.txt", "r", encoding="utf-8") as archivo:
            notas = archivo.readlines()

        resultados = [nota for nota in notas if palabra in nota.lower()]

        if resultados:
            print("\n🔍 RESULTADOS:")
            for nota in resultados:
                print(nota.strip())
        else:
            print("No se encontraron notas.")

    except FileNotFoundError:
        print("No existe el archivo de notas.")


def menu():
    while True:
        print("\nSISTEMA DE NOTAS")
        print("1. Agregar nota")
        print("2. Ver notas")
        print("3. Eliminar nota")
        print("4. Buscar nota")
        print("5. Salir")

        try:
            opcion = int(input("Elige una opción (1-5): "))

            if opcion == 1:
                agregar_nota()
            elif opcion == 2:
                ver_notas()
            elif opcion == 3:
                eliminar_nota()
            elif opcion == 4:
                buscar_nota()
            elif opcion == 5:
                print("Saliendo del sistema 👋")
                break
            else:
                print("Opción inválida")

        except ValueError:
            print("Error: ingresa un número válido")


menu()