# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJqgGxoW9IDNtbIGpbnGZGsj0iG7V6eE
"""

def agregar_nota():
    nota = input("Escribe tu nota: ")
    with open("notas.txt", "a", encoding="utf-8") as archivo:
        archivo.write(nota + "\n")
    print("Nota guardada correctamente ✅")


def ver_notas():
    try:
        with open("notas.txt", "r", encoding="utf-8") as archivo:
            notas = archivo.readlines()

        if not notas:
            print("No hay notas guardadas.")
        else:
            print("\n📒 TUS NOTAS:")
            for i, nota in enumerate(notas, start=1):
                print(f"{i}. {nota.strip()}")

    except FileNotFoundError:
        print("No existe el archivo de notas todavía.")


def menu():
    while True:
        print("\nSISTEMA DE NOTAS")
        print("1. Agregar nota")
        print("2. Ver notas")
        print("3. Salir")

        try:
            opcion = int(input("Elige una opción (1-3): "))

            if opcion == 1:
                agregar_nota()
            elif opcion == 2:
                ver_notas()
            elif opcion == 3:
                print("Saliendo del programa 👋")
                break
            else:
                print("Opción inválida")

        except ValueError:
            print("Error: ingresa un número válido")


menu()